[package]
name = "multiplayer-fps"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
rand = "0.8.5"
rapier3d = "0.23.0"
serde = "1.0.217"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bincode = "1.3.3"
